# environment settings
gpu_id: 1
checkpoint_dir: './saved/ml-1m/'
data_path: ./dataset/
save_dataset: true
show_progress: false
use_gpu: true
log_wandb : true
wandb_project : 'recbole-wandb'

# data settings
MAX_ITEM_LIST_LENGTH: 200
ITEM_ID_FIELD: item_id
user_inter_num_interval: '[5,inf)'
item_inter_num_interval: '[5,inf)'
load_col:
  inter:
  - user_id
  - item_id
  - rating
  - timestamp
threshold : {'rating':3}
# training settings
epochs: 50
train_batch_size: 256
learner: adam
learning_rate: 0.001
train_neg_sample_args:
  by: 1
  distribution: uniform
  dynamic: none
  strategy: by
eval_step: 5
stopping_step: 5
weight_decay: 0.0
loss_type: BPR
neg_sampling:
  uniform: 1

# evaluation settings 
eval_args:
  group_by: user
  mode: uni100
  order: TO
  split:
    LS: valid_and_test
repeatable: true
metrics:
- MRR
- NDCG
- Hit
topk:
- 1
- 5
- 10
eval_batch_size: 6464
valid_metric: MRR@10
eval_neg_sample_args:
  by: 100
  distribution: uniform
  strategy: by

n_layers: 2
n_heads: 2
# n_way : 1
n_blocks : 2

user_embedding_size : 256
item_embedding_size : 256

hidden_size : 64
inner_size: 256

hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'BPR'

seq_aggregate : true
u_cutoff : 0.6
i_cutoff : 0.6
s_attn_first : true